### PR TITLE
Sccache

### PR DESCRIPTION
**Pull request by jonashaag**

### CODE REVIEW

**Comment by jonashaag** [comment]
@wolfv pair debugging, any ideas?

```
FAILED: libmamba/CMakeFiles/libmamba-static.dir/src/core/shell_init.cpp.obj 

sccache C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\HostX64\x64\cl.exe  /nologo /TP -DGHC_WIN_DISABLE_WSTRING_STORAGE_TYPE -DJSON_DIAGNOSTICS=0 -DJSON_USE_IMPLICIT_CONVERSIONS=1 -DLIBMAMBA_EXPORTS -DREPROCXX_SHARED -DREPROC_SHARED -ID:\a\mamba\mamba\libmamba\include -ID:\a\mamba\mamba\libmamba\src -IC:\Users\runneradmin\micromamba\envs\build_env\Library\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /DNOMINMAX /MD /O2 /Ob2 /DNDEBUG -std:c++17 /showIncludes /Folibmamba\CMakeFiles\libmamba-static.dir\src\core\shell_init.cpp.obj /Fdlibmamba\CMakeFiles\libmamba-static.dir\libmamba-static.pdb /FS -c D:\a\mamba\mamba\libmamba\src\core\shell_init.cpp

D:\a\mamba\mamba\libmamba\include\mamba/core/util.hpp(175): warning C4067: unexpected tokens following preprocessor directive - expected a newline
d:\a\mamba\mamba\libmamba\include\mamba\core\environment.hpp(21): warning C4067: unexpected tokens following preprocessor directive - expected a newline
D:\a\mamba\mamba\libmamba\include\../data/micromamba.sh(91): fatal error C1021: invalid preprocessor command 'In'
```

**Comment by wolfv** [comment]
Ugh, there is some bash comments like `    # In dev-mode MAMBA_EXE is python.exe and on Windows` and for whatver reason it seems that this is interpreted as a preprocessor directive?

We could try removing these comments and see if that changes something. Or we find another way of inserting text into C++ although this is convenient.

**Comment by jonashaag** [comment]
@wolfv Ha, very good intuition, thanks for that!

```
D:\a\mamba\mamba\libmamba\include\../data/micromamba.sh(91): fatal error C1021: invalid preprocessor command 'FOO'
```

**Comment by jonashaag** [comment]
I guess it's because Visual Studio doesn't ignore those '#' in `R(...)` strings

**Comment by jonashaag** [comment]
Related https://github.com/mozilla/sccache/issues/116

**Comment by wolfv** [comment]
two comments left! :)

**Comment by jonashaag** [comment]
@wolfv works :rocket: now we just need a way to get the comments back

**Comment by wolfv** [comment]
One option would be to have a small preprocessing step that uses e.g . Python to compile the text files into a proper header file. A side benefit would be that we can keep the proper extension which will make editing these files easier :)

**Comment by jonashaag** [comment]
I think that would not change anything because sccache seems to be using the preprocessor output, which would stay the same. Unless we make the script in a way so that no raw strings are being used.

Or we wait for https://github.com/mozilla/sccache/issues/1127 to be fixed.

**Comment by wolfv** [comment]
We actually already have the python script :) https://github.com/mamba-org/mamba/blob/master/libmamba/data/bin2header.py

The output looks like this https://github.com/mamba-org/mamba/blob/master/libmamba/data/conda_exe.hpp and shouldn't give us any trouble.

**Comment by jonashaag** [comment]
Sweet, I can give it a shot if you tell me what's the best way to integrate this as preprocessing step in CMake

**Comment by jonashaag** [comment]
@wolfv I have no idea what I'm doing but this works :rocket:

**Comment by jonashaag** [comment]
Ha, an old friend:

```
AttributeError: module 'libmambapy' has no attribute 'QueryFormat'
```

Need to think where that's coming from. But sccache works.

**Comment by jonashaag** [comment]
@wolfv I tried to enable env caching for the Mamba CI but we have this problem:

```
CondaValueError: prefix already exists: /home/runner/micromamba/envs/build_env/envs/smalltestenv
```

Reason is that `envs/build_env` is cached from a previous run and includes `build_env/envs`.

Questions:

- Why is there another `envs/` inside `build_env`? Is that expected or a bug? Haven't seen such folder structure so far.
- Should we save the cache of `envs/build_env` immediately after the env was created in `provision-with-micromamba`, rather than at the end of the CI job?

**Pull request closed without merging**
